### PR TITLE
Fix authentication on IP change

### LINKED ISSUE #68: Problem when a memcached server changes IP address
We have to configure our client with `failureMode=true`, and we are getting errors like this when a memcached server gets down and comes back with a different IP:
```
net.rubyeye.xmemcached.exception.MemcachedException: Session(192.168.1.41:11211) has been closed
	at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:512)
	at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:317)
	at net.rubyeye.xmemcached.XMemcachedClient.fetch0(XMemcachedClient.java:644)
	at net.rubyeye.xmemcached.XMemcachedClient.get0(XMemcachedClient.java:1085)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1043)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1054)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1076)
```

The old IP was `192.168.1.41` and the new one is `192.168.1.44`. When the server recovers with the new IP we can see logs like:
> com.google.code.yanf4j.core.impl.AbstractController:? Add a session: 192.168.1.44:11211

However, the client is still using sessions with the old IP that are closed.

I have been debugging a bit and found that in the class `net.rubyeye.xmemcached.impl.MemcachedConnector` there is an attribute called `sessionMap` that contains sessions with both the old and new IP, because the new sessions do not override the old ones, and then all those sessions are passed to the session locator in the method `updateSessions()`. I think the session locator should receive only the sessions with the new IP.

Please could you take a look?

### PR DESCRIPTION
**Pull request by saschat**
This fixes #68

The problem was the the `AuthInfoMap` stores an `AuthInfo` for a server's `InetSocketAddress`. Unfortunately, the `InetSocketAddress` hash is based on the resolved IP which can change. For this reason I changed the `AuthInfoMap` to store the `AuthInfo` based on the servers (hostname:port) string.

Note, I tried to fix this problem without changing any public interface but I don't like it. I could also change the `MemcachedClient.getAuthInfoMap()` from `public Map<InetSocketAddress, AuthInfo> getAuthInfoMap();` to `public Map<String, AuthInfo> getAuthInfoMap();` instead. This would be a bit nicer but change the interface. What do you think?

Review by commit. The first commit only removes trailing whitespaces. The code changes are all in the second commit.

### CODE REVIEW

**Comment by killme2008** [comment]
Can you format the code with google style?

https://github.com/killme2008/xmemcached/blob/master/eclipse-java-google-style.xml

**Comment by saschat** [comment]
I tried to do that but then it changes all line endings to line feed. I guess because I am on a Linux system. But maybe I do something wrong. What formatting tool do you use?

**Comment by saschat** [comment]
Btw. the `eclipse-java-google-style.xml` also specifies tabs as spaces but you use tabs in all files. Are you sure the current code is formatted with this style?

**Comment by saschat** [comment]
@killme2008 Or do you prefer if I format the whole project with the google style file in this PR?

**Comment by killme2008** [comment]
@saschat hi, i will format the code with google style, and then i can review your PR.

**Comment by saschat** [comment]
Ok, perfect!

Btw. I would also add the formatter to the `pom.xml` file so that it always happens automatically:
```
<plugin>
	<groupId>net.revelc.code.formatter</groupId>
	<artifactId>formatter-maven-plugin</artifactId>
	<version>2.7.2</version>
	<configuration>
		<configFile>${project.basedir}/eclipse-java-google-style.xml</configFile>
		<lineEnding>CRLF</lineEnding>
	</configuration>
	<executions>
		<execution>
			<goals>
				<goal>format</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

Like this it will always format the code when it is compiled or it can be done manually with `mvn formatter:format`.

**Comment by killme2008** [comment]
@saschat  I added the plugin to format the code and formatted all code on master branch , but set `lineEncoding` as `LF`.

Can you create a new PR that is checked out from master again?

**Comment by saschat** [comment]
Ok, done -> #81

**Pull request closed without merging**
