### PR TITLE
Update benchmark project

### PR DESCRIPTION
**Pull request by atais**
I need to run some benchmarks regarding the lib and I thought using the existing project could be useful. However, it's not easy to run now, because there is no build tool attached.

This branch will evolve into updating the jars and comparing versions.
For some reason, GitHub treats moved files as +/-

Roadmap:
- [x] added maven and removed most of the jar files
- [x] using `docker` as default memcache instance
- [x] using SLF4J for logging
- [x] saving bench results to csv file
- [x] HTML report can generate graphs from CSV, no processing with java.
- [x] rerun old tests for comparison
- [x] update Xmemcached 
- [x] add new versions test results into report

Worth doing:
- review the benchmarking method
- update spymemcached
- update Memcached-Java-Client

### CODE REVIEW

**Comment by killme2008** [comment]
Good job, thanks.

**Comment by atais** [comment]
OK, so I am halfway there.

What worries me greatly is that on my machine I got completely different results than you did :scream: It might be because I am running it all on localhost...

I am now planning to improve the logging and graphing so it would be easier to repeat the tests and post updated results.

**Comment by atais** [comment]
OK I think I have done as much as I could here.

**Comment by atais** [comment]
@killme2008 any comments or issues?

**Comment by atais** [comment]
@killme2008 CI is still not triggered here, so I guess you need to work on the project configuration

**Comment by killme2008** [comment]
@atais  Thanks a lot, a really good job.

**Pull request merged**
